# Generated by Django 4.2.13 on 2024-05-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updates_at", models.DateTimeField(auto_now_add=True)),
                ("sub_category", models.CharField(max_length=5000)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updates_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=5000)),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updates_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("receipts", models.CharField(max_length=200, null=True)),
                ("payments", models.CharField(max_length=200, null=True)),
                ("for_edit", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ManyToManyField(to="dashboard.category")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="category",
            name="main_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashboard.maincategory"
            ),
        ),
    ]
