# Generated by Django 5.0.6 on 2024-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pendingreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PendingReports',
        ),
    ]
