# Generated by Django 5.0.6 on 2024-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='payments',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='receipts',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
