# Generated by Django 5.0.6 on 2024-06-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_reports_payments_alter_reports_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
