# Generated by Django 5.0.6 on 2024-06-06 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_reports_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='modification_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reports',
            name='modification_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
