# Generated by Django 5.0.6 on 2024-06-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('manager', 'Manager')], default='admin', max_length=20),
        ),
    ]
